apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate-deployment
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
      image: nginx:1.21
      ports:
      - containerPort: 80
      name: nginx